### ISSUE TITLE
client hangs when using console callback

### ISSUE THREAD

**Issue by stfran** [DanMcInerney/pymetasploit3#2]
I'm doing some basic stuff to test functionality and I run into an issue where the client seems to hang when I try to log out. It only happens when I use the console callback (line 17). By hang, I mean the program never makes it to exit(0) and I have to ctrl-C to close it. When I run without line 17, the behavior is as expected and the program exits without error. I'd like to be able to build upon my callback function, but I need to get this solved, first. Any help is greatly appreciated. 

![image](https://user-images.githubusercontent.com/36734136/55663663-5ec0ba80-57ef-11e9-9699-ace033e90ef7.png)

![image](https://user-images.githubusercontent.com/36734136/55663681-87e14b00-57ef-11e9-8fb6-812f091e0c29.png)

**Comment by stfran** [comment]
Actually, this isn't happening anymore since I reinstalled, but now I have other issues that are causing not to run. I will close this, for now, and do the other issues.

**Comment by DanMcInerney** [comment]
Hmm interesting. Not sure what would cause that as by default I have set the login function to add a permanent API token rather than the 5m expiring one that you used to get by default. I'm very in the other bugs you find.

**Comment by stfran** [comment]
I just posted a couple, but I'm not a python expert and I'm not sure if my fixes are appropriate, but I provided that in the issues.
