### ISSUE TITLE
Module not found error in several files

### ISSUE THREAD

**Issue by stfran** [DanMcInerney/pymetasploit3#4]
I get module not found errors in the import lines that contain 'src' throughout the code. msfrpc.py, msfconsole.py and the tests. the offending line is from src.metasploit... I corrected by removing src because the top level that is installed with setup.py is the metasploit directory and not the src directory.

**Comment by DanMcInerney** [comment]
I think I fixed this. I haven't tested the fix yet since I'm using a pipenv environment instead of setup.py for library install but I'll circle back around and test the fix later.
