### ISSUE TITLE
can't install new setup.py

### ISSUE THREAD

**Issue by stfran** [DanMcInerney/pymetasploit3#6]
I did some googling on packages and it looks good to me (again, novice, here), but for some reason the metasploit directory isn't getting installed. 

root@kali:/Documents/pymetasploit3# python3 setup.py install
running install
running bdist_egg
running egg_info
creating pymetasploit.egg-info
writing pymetasploit.egg-info/PKG-INFO
writing dependency_links to pymetasploit.egg-info/dependency_links.txt
writing requirements to pymetasploit.egg-info/requires.txt
writing top-level names to pymetasploit.egg-info/top_level.txt
writing manifest file 'pymetasploit.egg-info/SOURCES.txt'
error: package directory 'metasploit' does not exist
root@kali:/Documents/pymetasploit3#

**Comment by DanMcInerney** [comment]
Yeah I've never figured out how to do setup.py right. I'll have to figure
that out here soon.

**Comment by DanMcInerney** [comment]
I'm in the process of figuring this out. Hang tight, ETA sometime in the next week or two I'll have this fixed.

**Comment by DanMcInerney** [comment]
I think I got it this time. Worked in my pipenv environment to do a ```python3 install pymetasploit3``` from the top pymetasploit3 directory.
