### ISSUE TITLE
[Suggestion] Add info property to MsfModule

### ISSUE THREAD

**Issue by scmanjarrez** [DanMcInerney/pymetasploit3#82]
Hi, 
What do you think about adding "info" property to MsfModule? 
Right now, every element of "info" is set as a property, but we don't know exactly what attributes are from the module info because they are prefiltered, the raw information is in **self._info** which is not accessible.
I'm proposing to add a new property returning **self._info** with the raw information from msfrpc.
```python
    @property
    def info(self):
        """
        Get information about the module
        """
        return self._info
```

**Comment by DanMcInerney** [comment]
I think it's a good idea that I'm not going to implement because I don't get to use this project much at work but would very much love a PR that implements it.

**Comment by scmanjarrez** [comment]
You already merged the PR :sweat_smile:, we can close this issue.
